### ISSUE TITLE
stream.pause() not work, pipe2jpeg continue emitting data

### ISSUE THREAD

**Issue by voxsoftware** [kevinGodell/pipe2jpeg#14]
The pipe2jpeg stream.pause() doesn't work as expected, pipe2jpeg continue emitting "jpeg" event.
Is a big problem, without a correct pause/resume function; for example reading big files and "long" image process logic, can cause an unexpected high memory/cpu usage.

**Comment by voxsoftware** [comment]
https://github.com/kevinGodell/pipe2jpeg/pull/15

**Comment by kevinGodell** [comment]
While I do appreciate your interest and PR, I can't see how I would ever need to pause jpeg parsing. If you have control of the data being pushed into it, wouldn't you just stop it at that point? Pausing it just causes the data being pushed into it to be lost. Resuming will cause unexpected behaviour since a moderate to large jpeg usually spans across multiple chunks of buffer and some of it may already be saved in the internal array of buffer chunks. Can you give a working example of how and why this would be used in the real world?

**Comment by kevinGodell** [comment]
I tried to meet you halfway by making _transform easier for you to override the prototype.
the new code looks like:
```
_transform(chunk, encoding, callback) {
    this._parseJpeg(chunk);
    callback();
  }
```
You could add this feature to your own by doing:
```
Pipe2Jpeg.prototype._transform = function(chunk, encoding, callback) {
  this._parseJpeg(chunk);
  if (this.isPaused()) {
    this.once('resume', callback);
  } else {
    callback();
  }
};
```
I performed multiple tests and pausing the stream seemed to increase the memory usage. I am not really sure what the expectation is.
